### ISSUE TITLE
hello.md not present

### ISSUE THREAD

**Issue by mananaboshi** [Riseley/think_bubble#4]
bug bug bug

**Comment by mananaboshi** [comment]
new bug bug 
asdf
adsf
asf
asd
fa
sdf
as
df
asf

fad
sdf
ffffffffffffff

**Comment by Riseley** [comment]
la;sdjflkjsdflalsdj kajsdflja sldfjlsdj lsdf

**Comment by Riseley** [comment]
alsjflksdjflzslfjl sjdfljalsdjfl ajsldfj

**Comment by Riseley** [comment]
Fixed in https://github.com/Riseley/think_bubble/commit/268070e03b2093b148acca42c45053d51c13acad
